
# Updated data, so fixing tables

```{r}
library(here)
library(janitor)
library(tidyverse)
library(dplyr)

sensor_range_df <- read_csv("data/Sensor Range.csv") %>% clean_names()
platform_range_df <- read_csv("data/Platform Range.csv") %>% clean_names()
satellites <- read_csv("data/satellites.csv") %>% clean_names()
characteristics <- read_csv("data/characteristics.csv") %>% clean_names()
iuu_type_index <- read_csv("data/IUU Type Index.csv") %>% clean_names() %>% 
  select(!detection_area) %>% 
  select(!observable)

```

```{r}


platform_range_vec <- platform_range_df[3, -1]/2 #divide by 2 so that the platform can return to deployment base
platform_range_vec[4] <- platform_range_vec[4]*2 # excludes process for smart buoy
platform_range_vec[7] <- platform_range_vec[7]*2 # excludes process for onshore command center
platform_range_vec


# Initialize area_df with the Index column
area_df <- data.frame(index = sensor_range_df$index)
pi <- pi

# Multiply each sensor range by each value in platform_range_vec
for (sensor in names(sensor_range_df)[-1]) {
  for (platform in names(platform_range_vec)) {
    column_name <- paste(sensor, "by", platform)
    area_df[[column_name]] <- pi * (sensor_range_df[[sensor]] + platform_range_vec[[platform]])^2 #make the coverage area a circle  
  }
}

# write.csv(area_df, file = "platform_sensor_coverage_area.csv", row.names = FALSE)

merged_index_df <- merge(iuu_type_index, area_df, by.x = "granularity_index", by.y = "index")


```

```{r}
# exclude the first column
columns_to_bin <- names(area_df)[-1]

#convert to numeric vector to cut 
area_vec <- area_df %>%
  select(columns_to_bin) %>%
  unlist()

#define number of bins
num_bins <- 3

#cut the numeric vector into equally sized bins
area_bins <- cut_number(area_vec, n = num_bins)

# Extract unique levels and convert to numeric
unique_levels <- unique(as.character(area_bins))
numeric_levels <- sort(as.numeric(gsub("\\[|\\(|,.*", "", unique_levels)))

local_lower <- numeric_levels[1]
local_upper <- numeric_levels[2]
regional_lower <- numeric_levels[2]
regional_upper <- numeric_levels[3]
international_lower <- numeric_levels[3]

# Create a data frame with bin index, lower, and upper ranges
bin_ranges_df <- data.frame(
  Bin = c("Local", "Regional", "High Seas"),
  Lower = numeric_levels[1:num_bins],
  Upper = c(numeric_levels[-1], Inf)
)

# fix the bin ranges based on new data
# write_csv(bin_ranges_df, "./bin_ranges.csv")
```


### Platform + sensor characteristics dataframe
```{r}
# Create df for sensor_platform combinations 
sensor_platform_combinations <- crossing(
  sensor = colnames(sensor_range_df)[-1], 
  platform = colnames(platform_range_df)[-1]
)

# Create a function to look up cost values based on sensor or platform
get_cost <- function(value) {
  cost <- characteristics %>%
    filter(monitoring_method == value) %>%
    pull(cost)
  
  if (length(cost) == 0) {  # No matching cost found
    return(NA)  # Return NA to indicate missing cost
  } else {
    return(cost[1])  # Return the first matching cost if there are multiple (or just one)
  }
}

cost_vec <- numeric(nrow(sensor_platform_combinations))

for (i in seq_len(nrow(sensor_platform_combinations))) {
  sensor_value <- sensor_platform_combinations$sensor[i]
  platform_value <- sensor_platform_combinations$platform[i]
  
  sensor_cost <- get_cost(sensor_value)
  platform_cost <- get_cost(platform_value)
  
  # Check for NA values explicitly and assign NA to cost_vec[i] if either cost is NA
  if (is.na(sensor_cost) || is.na(platform_cost)) {
    cost_vec[i] <- NA  # Assign NA directly if either cost is not available
  } else {
    # take the maximum cost if both costs available
    cost_vec[i] <- max(sensor_cost, platform_cost)
  }
}

sensor_platform_combinations$total_cost <- cost_vec


# write_csv(sensor_platform_combinations, "./data/sensor_platform_combinations_cost.csv")

sensor_platform_combinations_cost_df <- read_csv("data/sensor_platform_combinations_cost.csv")




sensor_platform_combinations_cost_df$sensor_platform <- with(sensor_platform_combinations_cost_df, paste(sensor, "by", platform))



```


```{r}
index_tidy <- merged_index_df %>%
  select(-granularity_index) %>% 
  pivot_longer(cols = starts_with("long_range_camera by usv"):ends_with("hydroacoustics by onboard"), 
               names_to = "sensor_platform", values_to = "value") %>%
  pivot_wider(names_from = iuu_type, values_from = value)


# now want to add on cost and data types
# need to join the datasets!
index_tidy_more <- index_tidy %>%
  left_join(sensor_platform_combinations_cost_df %>% 
              select(sensor_platform, total_cost, total_cost_bins, data_type),
            by = "sensor_platform")

index_tidy_more <- index_tidy_more %>% 
  mutate_if(is.numeric, round)



```


```{r}
combination_matrix <- read_csv("data/combination_matrix.csv") %>% clean_names()

# We want to get rid of the rows that have sensor + platform pairings with a zero as depicted in the combination matrix.

zero_combinations <- which(combination_matrix == 0, arr.ind = TRUE)
zero_combinations_named <- data.frame(
  platform = rownames(combination_matrix)[zero_combinations[, 1]],
  sensor = colnames(combination_matrix)[zero_combinations[, 2]])

test <- as.numeric(zero_combinations_named$platform)
to_replace <- combination_matrix$platform[test]

zero_combinations_named$platform <- to_replace

zero_combinations_named$sensor_platform <- with(zero_combinations_named, paste(sensor, "by", platform))

zero_combinations_named <- zero_combinations_named %>% 
  select(sensor_platform)


# Write to csv
#write_csv(filtered_bad_pairings, "./sensor_platform_removed_bad_pairings.csv")


```


```{r}
# Get bad pairings out of merged_index aka index_tidy_more

merged_index_removed_bad_combos <- index_tidy_more %>%
  anti_join(zero_combinations_named, by = c("sensor_platform"))


# write_csv(merged_index_removed_bad_combos, "./merged_index_removed_bad_combos.csv")

```

